### ISSUE TITLE
`add` and `edit` commands error if $EDITOR set to "vim -u ~/my-vimrc"

### ISSUE THREAD

**Issue by tddschn** [gnebbia/kb#4]
## Expected Behavior
`add` and `edit` commands work.

## Actual Behavior
`add` and `edit` commands don't work if $EDITOR is set to "vim -u ~/my-vimrc", but work if set to just "vim".

```zsh
$ echo "${EDITOR}"
vim -u ~/my-vimrc

$ kb add -t 'test title test'
Traceback (most recent call last):
  File "/usr/local/bin/kb", line 33, in <module>
    sys.exit(load_entry_point('kb==0.1.1', 'console_scripts', 'kb')())
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/main.py", line 62, in main
    dispatch(cmd, cmd_params, config=DEFAULT_CONFIG)
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/main.py", line 52, in dispatch
    return COMMANDS[function](*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kb-0.1.1-py3.8.egg/kb/commands/add.py", line 71, in add
    call([config["EDITOR"], Path(category_path, title)])
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vim -u ~/my-vimrc'
```

Problems seem to be at the line `call([config["EDITOR"], Path(category_path, title)])` in `kb/commands/add.py` and `kb/commands/view.py`. 

## Steps to Reproduce the Problem

```zsh
touch ~/my-vimrc
EDITOR="vim -u ~/my-vimrc" kb add -t 'new title'
EDITOR="vim -u ~/my-vimrc" kb view -t 'new title'
```

## Specifications

  - Version: Python 3.8.5
  - Platform: macOS Catalina 10.15.6
  - Subsystem: N/A

**Comment by gnebbia** [comment]
Thanks for the suggestion!

Fixed with commit 699ba35

**Comment by tddschn** [comment]
Thanks for the quick fix!

I'm not familiar with `setup.py` and couldn't figure out how to upgrade `kb`, can you help me? 

Here's what I tried:
```
git pull origin master # checked, add.py and edit.py fixed with "shell=True" added to call()
python setup.py install
python setup.py install --force
```
and it seems that these 2 commands still don't work.

**Comment by gnebbia** [comment]
do this:
within the kb direectory, execute:
```python
pip install --upgrade .  # there is a dot after upgrade ;)
```
Let me know if it works!

**Comment by tddschn** [comment]
Thanks! :)

After upgrading `kb` with  `pip install --upgrade .`, `add` works but `edit` doesn't. 

I'll open a PR and try to fix it :)

**Comment by gnebbia** [comment]
Ok, fixed again, sorry, my bad, I did not update the edit module!
Thanks for warning me!
Can you update and tell me if it is solved now?

**Comment by tddschn** [comment]
Yes, thanks! :)

**Comment by gnebbia** [comment]
Ok I fixed it again and removed shell=True, since it may cause security issues through command injection.
Try to see if it works now, I tested and seems ok now!

**Comment by tddschn** [comment]
Yes it works! Thank you :)

**Comment by gnebbia** [comment]
You are welcome! Happy to be helpful!
